window.tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "tertiary": "#ffffff",
                "inverse-primary": "#5d5f5f",
                "inverse-surface": "#e2e2e2",
                "on-tertiary-container": "#656466",
                "on-tertiary-fixed": "#1b1b1d",
                "on-secondary-fixed": "#1a1b1f",
                "tertiary-container": "#e4e2e4",
                "secondary": "#c7c6ca",
                "surface-container-low": "#1b1b1b",
                "on-tertiary": "#303032",
                "primary-fixed": "#e2e2e2",
                "on-primary-fixed-variant": "#454747",
                "outline-variant": "#444748",
                "surface-container-highest": "#353535",
                "secondary-fixed": "#e3e2e6",
                "error-container": "#93000a",
                "error": "#ffb4ab",
                "on-tertiary-fixed-variant": "#474649",
                "on-primary-container": "#636565",
                "on-primary-fixed": "#1a1c1c",
                "primary-container": "#e2e2e2",
                "outline": "#8e9192",
                "surface-tint": "#c6c6c7",
                "surface": "#131313",
                "surface-variant": "#353535",
                "secondary-container": "#48494c",
                "on-primary": "#2f3131",
                "on-background": "#e2e2e2",
                "surface-container": "#1f1f1f",
                "tertiary-fixed-dim": "#c8c6c8",
                "on-secondary-container": "#b8b8bc",
                "surface-bright": "#393939",
                "on-secondary-fixed-variant": "#46474a",
                "on-error": "#690005",
                "tertiary-fixed": "#e4e2e4",
                "on-secondary": "#2f3034",
                "inverse-on-surface": "#303030",
                "background": "#131313",
                "surface-container-lowest": "#0e0e0e",
                "on-surface-variant": "#c4c7c8",
                "surface-dim": "#131313",
                "on-error-container": "#ffdad6",
                "secondary-fixed-dim": "#c7c6ca",
                "on-surface": "#e2e2e2",
                "primary-fixed-dim": "#c6c6c7",
                "primary": "#ffffff",
                "surface-container-high": "#2a2a2a"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "stack-md": "16px",
                "unit": "4px",
                "stack-lg": "32px",
                "margin-mobile": "20px",
                "stack-sm": "8px",
                "gutter": "12px"
            },
            "fontFamily": {
                "display-countdown-mobile": ["Inter"],
                "headline-lg": ["Inter"],
                "body-lg": ["Inter"],
                "display-countdown": ["Inter"],
                "headline-sm": ["Inter"],
                "body-sm": ["Inter"],
                "label-caps": ["Inter"]
            },
            "fontSize": {
                "display-countdown-mobile": ["48px", {"lineHeight": "1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
                "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400"}],
                "display-countdown": ["64px", {"lineHeight": "1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
                "headline-sm": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "body-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400"}],
                "label-caps": ["11px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700"}]
            }
        },
    },
};